// This file was generated by lezer-generator. You probably shouldn't edit it.
export const Comment = 1,
  Document = 2,
  Property = 3,
  PropertyName = 4,
  Object = 7,
  Array = 10,
  Null = 11,
  Number = 12,
  String = 13,
  Bytes = 14,
  True = 15,
  False = 16;
