name: deploy

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4

      - run: node ./scripts/login.mts
        env:
          INNOAI_TECH_REGISTRY_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: just ts::dep
      - run: just webapp::setup-e2e
      - run: just ci

  release:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4

      - run: node ./scripts/login.mts
        env:
          INNOAI_TECH_REGISTRY_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: just ts::dep
      - run: just pub
      - run: just build
      - run: just webapp::build-all

      - uses: JamesIves/github-pages-deploy-action@v4.9.0
        with:
          folder: public/openapi-playground
          repository-name: innoai-tech/openapi-playground
          branch: main
          ssh-key: ${{ secrets.OPENAPI_PLAYGROUND_DEPLOY_KEY }}
          clean: true

      - uses: JamesIves/github-pages-deploy-action@v4.9.0
        with:
          folder: public/vuekit
          branch: gh-pages
          clean: true
